export const STORIES_LIST_REQUEST = "STORIES_LIST_REQUEST";
export const STORIES_LIST_SUCCESS = "STORIES_LIST_SUCCESS";
export const STORIES_LIST_FAIL = "STORIES_LIST_FAIL";
export const STORIES_LIST_RESET = "STORIES_LIST_RESET";

export const STORIES_TOP_REQUEST = "STORIES_TOP_REQUEST";
export const STORIES_TOP_SUCCESS = "STORIES_TOP_SUCCESS";
export const STORIES_TOP_FAIL = "STORIES_TOP_FAIL";
export const STORIES_TOP_RESET = "STORIES_TOP_RESET";

export const STORIES_LATEST_REQUEST = "STORIES_LATEST_REQUEST";
export const STORIES_LATEST_SUCCESS = "STORIES_LATEST_SUCCESS";
export const STORIES_LATEST_FAIL = "STORIES_LATEST_FAIL";
export const STORIES_LATEST_RESET = "STORIES_LATEST_RESET";

export const MY_STORIES_REQUEST = "MY_STORIES_REQUEST";
export const MY_STORIES_SUCCESS = "MY_STORIES_SUCCESS";
export const MY_STORIES_FAIL = "MY_STORIES_FAIL";
export const MY_STORIES_RESET = "MY_STORIES_RESET";

export const STORY_DETAILS_REQUEST = "STORY_DETAILS_REQUEST";
export const STORY_DETAILS_SUCCESS = "STORY_DETAILS_SUCCESS";
export const STORY_DETAILS_FAIL = "STORY_DETAILS_FAIL";
export const STORY_DETAILS_RESET = "STORY_DETAILS_RESET";

export const STORY_WRITE_DETAILS_REQUEST = "STORY_WRITE_DETAILS_REQUEST";
export const STORY_WRITE_DETAILS_SUCCESS = "STORY_WRITE_DETAILS_SUCCESS";
export const STORY_WRITE_DETAILS_FAIL = "STORY_WRITE_DETAILS_FAIL";
export const STORY_WRITE_DETAILS_RESET = "STORY_WRITE_DETAILS_RESET";

export const STORY_WRITE_CONTENT_REQUEST = "STORY_WRITE_CONTENT_REQUEST";
export const STORY_WRITE_CONTENT_SUCCESS = "STORY_WRITE_CONTENT_SUCCESS";
export const STORY_WRITE_CONTENT_FAIL = "STORY_WRITE_CONTENT_FAIL";
export const STORY_WRITE_CONTENT_RESET = "STORY_WRITE_CONTENT_RESET";

export const STORY_DELETE_REQUEST = "STORY_DELETE_REQUEST";
export const STORY_DELETE_SUCCESS = "STORY_DELETE_SUCCESS";
export const STORY_DELETE_FAIL = "STORY_DELETE_FAIL";
export const STORY_DELETE_RESET = "STORY_DELETE_RESET";

export const STORY_ADD_REVIEW_REQUEST = "STORY_ADD_REVIEW_REQUEST";
export const STORY_ADD_REVIEW_SUCCESS = "STORY_ADD_REVIEW_SUCCESS";
export const STORY_ADD_REVIEW_FAIL = "STORY_ADD_REVIEW_FAIL";
export const STORY_ADD_REVIEW_RESET = "STORY_ADD_REVIEW_RESET";

export const STORY_REPORT_REQUEST = "STORY_REPORT_REQUEST";
export const STORY_REPORT_SUCCESS = "STORY_REPORT_SUCCESS";
export const STORY_REPORT_FAIL = "STORY_REPORT_FAIL";
export const STORY_REPORT_RESET = "STORY_REPORT_RESET";
